export const awsRegions: { description: string; code: AWSRegion }[] = [
  { description: 'Europe (Ireland)', code: 'eu-west-1' },
  { description: 'Europe (London)', code: 'eu-west-2' },
  { description: 'Europe (Frankfurt)', code: 'eu-central-1' },
  { description: 'Europe (Milan)', code: 'eu-south-1' },
  { description: 'Europe (Paris)', code: 'eu-west-3' },
  { description: 'Europe (Stockholm)', code: 'eu-north-1' },
  { description: 'US East (Ohio)', code: 'us-east-2' },
  { description: 'US East (N. Virginia)', code: 'us-east-1' },
  { description: 'US West (N. California)', code: 'us-west-1' },
  { description: 'US West (Oregon)', code: 'us-west-2' },
  { description: 'Canada (Central)', code: 'ca-central-1' },
  { description: 'Africa (Cape Town)', code: 'af-south-1' },
  { description: 'Asia Pacific (Hong Kong)', code: 'ap-east-1' },
  { description: 'Asia Pacific (Mumbai)', code: 'ap-south-1' },
  { description: 'Asia Pacific (Osaka-Local)', code: 'ap-northeast-3' },
  { description: 'Asia Pacific (Seoul)', code: 'ap-northeast-2' },
  { description: 'Asia Pacific (Singapore)', code: 'ap-southeast-1' },
  { description: 'Asia Pacific (Sydney)', code: 'ap-southeast-2' },
  { description: 'Asia Pacific (Tokyo)', code: 'ap-northeast-1' },
  // { description: 'China (Beijing)', code: 'cn-north-1' },
  // { description: 'China (Ningxia)', code: 'cn-northwest-1' },
  { description: 'Middle East (Bahrain)', code: 'me-south-1' },
  { description: 'South America (São Paulo)', code: 'sa-east-1' }
];
